// Class: ReadMLPBFGS
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBFGS
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.18/04       [397828]
Creator        : edo
Date           : Wed Feb 26 10:54:08 2020
Host           : Linux edo-MSI 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/edo/UbuntuData/Documents/AnalysisComo/MultivariateAnaysis
Training events: 10000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "250" [Number of training cycles]
HiddenLayers: "N+9" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "20" [Test for overtraining performed at each #th epochs]
Tau: "7.000000e+00" [LineSearch "size step"]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 3
cs                            cs                            cs                            cs                                                              'F'    [0.396428465843,1.14327037334]
tstart                        tstart                        tstart                        tstart                                                          'F'    [3154,3193]
r95                           r95                           r95                           r95                                                             'F'    [0.543500006199,28.4575004578]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBFGS : public IClassifierReader {

 public:

   // constructor
   ReadMLPBFGS( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLPBFGS" ),
        fNvars( 3 )
   {
      // the training input variables
      const char* inputVars[] = { "cs", "tstart", "r95" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBFGS() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][3];
   double fScal_1[3][3];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[3];
   double fVmax[3];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[3];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[13][4];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][13];   // weight matrix from layer 1 to 2

};

inline void ReadMLPBFGS::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 1.61069429255737;
   fWeightMatrix0to1[1][0] = -1.25588544041486;
   fWeightMatrix0to1[2][0] = 0.431770386270045;
   fWeightMatrix0to1[3][0] = 5.33520006725909;
   fWeightMatrix0to1[4][0] = -7.77472916166805;
   fWeightMatrix0to1[5][0] = 2.49097545206311;
   fWeightMatrix0to1[6][0] = 0.0233021739802366;
   fWeightMatrix0to1[7][0] = 1.70758790149754;
   fWeightMatrix0to1[8][0] = -23.9661900505966;
   fWeightMatrix0to1[9][0] = -15.1525940054607;
   fWeightMatrix0to1[10][0] = 0.869691725377227;
   fWeightMatrix0to1[11][0] = -3.71926649347827;
   fWeightMatrix0to1[0][1] = 2.4397493944405;
   fWeightMatrix0to1[1][1] = 1.80392799483707;
   fWeightMatrix0to1[2][1] = -1.53940992371363;
   fWeightMatrix0to1[3][1] = -3.17031298756107;
   fWeightMatrix0to1[4][1] = -9.15577402788629;
   fWeightMatrix0to1[5][1] = 15.1545057954173;
   fWeightMatrix0to1[6][1] = -1.31833943998609;
   fWeightMatrix0to1[7][1] = 1.84784183462052;
   fWeightMatrix0to1[8][1] = -11.6788216192713;
   fWeightMatrix0to1[9][1] = -10.9327166711364;
   fWeightMatrix0to1[10][1] = 3.1288997914648;
   fWeightMatrix0to1[11][1] = -5.8611900600626;
   fWeightMatrix0to1[0][2] = -0.295988461222597;
   fWeightMatrix0to1[1][2] = 7.24652874906772;
   fWeightMatrix0to1[2][2] = 2.00660525124525;
   fWeightMatrix0to1[3][2] = 6.39872523681501;
   fWeightMatrix0to1[4][2] = 4.56606099454349;
   fWeightMatrix0to1[5][2] = -4.38750992557766;
   fWeightMatrix0to1[6][2] = 17.6820946613035;
   fWeightMatrix0to1[7][2] = 0.431234529044533;
   fWeightMatrix0to1[8][2] = -3.91439839172283;
   fWeightMatrix0to1[9][2] = -5.11998798744578;
   fWeightMatrix0to1[10][2] = -3.14615403249617;
   fWeightMatrix0to1[11][2] = 5.95702853640668;
   fWeightMatrix0to1[0][3] = -3.6037292855643;
   fWeightMatrix0to1[1][3] = -8.47089366145676;
   fWeightMatrix0to1[2][3] = -3.00761846664695;
   fWeightMatrix0to1[3][3] = -9.41945277394807;
   fWeightMatrix0to1[4][3] = 0.958979294735233;
   fWeightMatrix0to1[5][3] = 3.15585609396375;
   fWeightMatrix0to1[6][3] = 18.6226532775844;
   fWeightMatrix0to1[7][3] = 3.02500927508939;
   fWeightMatrix0to1[8][3] = 2.70525440558598;
   fWeightMatrix0to1[9][3] = 16.187973106674;
   fWeightMatrix0to1[10][3] = 4.3822747594116;
   fWeightMatrix0to1[11][3] = -10.3451203117876;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.7117929825057;
   fWeightMatrix1to2[0][1] = -4.78958348486738;
   fWeightMatrix1to2[0][2] = 2.09969393077865;
   fWeightMatrix1to2[0][3] = -4.693717212673;
   fWeightMatrix1to2[0][4] = -7.85404438390133;
   fWeightMatrix1to2[0][5] = -17.5528812352079;
   fWeightMatrix1to2[0][6] = -24.7420935773209;
   fWeightMatrix1to2[0][7] = 1.30737597195166;
   fWeightMatrix1to2[0][8] = -18.1328659642348;
   fWeightMatrix1to2[0][9] = 2.14312267685469;
   fWeightMatrix1to2[0][10] = 4.19309271437278;
   fWeightMatrix1to2[0][11] = -0.396552633213206;
   fWeightMatrix1to2[0][12] = -2.65204220149255;
}

inline double ReadMLPBFGS::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)3) {
      std::cout << "Input vector needs to be of size " << 3 << std::endl;
      return 0;
   }

   std::array<double, 13> fWeights1 {{}};
   std::array<double, 1> fWeights2 {{}};
   fWeights1.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<12; o++) {
      std::array<double, 4> buffer; // no need to initialise
      for (int i = 0; i<4 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][3];
      for (int i=0; i<4; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<12; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<1; o++) {
      std::array<double, 13> buffer; // no need to initialise
      for (int i=0; i<13; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<13; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights2[o] = OutputActivationFnc(fWeights2[o]);
   } // loop over o

   return fWeights2[0];
}

double ReadMLPBFGS::ActivationFnc(double x) const {
   // fast hyperbolic tan approximation
   if (x > 4.97) return 1;
   if (x < -4.97) return -1;
   float x2 = x * x;
   float a = x * (135135.0f + x2 * (17325.0f + x2 * (378.0f + x2)));
   float b = 135135.0f + x2 * (62370.0f + x2 * (3150.0f + x2 * 28.0f));
   return a / b;
}
double ReadMLPBFGS::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadMLPBFGS::Clear()
{
}
inline double ReadMLPBFGS::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform_1()
{
   double fMin_1[3][3];
   double fMax_1[3][3];
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.81289345026;
   fMax_1[0][0] = 1.14327037334;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = 0.396428465843;
   fMax_1[1][0] = 1.13690698147;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = 0.396428465843;
   fMax_1[2][0] = 1.14327037334;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = 3162;
   fMax_1[0][1] = 3192;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = 3154;
   fMax_1[1][1] = 3193;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = 3154;
   fMax_1[2][1] = 3193;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = 0.947000026703;
   fMax_1[0][2] = 6.58699989319;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = 0.543500006199;
   fMax_1[1][2] = 28.4575004578;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = 0.543500006199;
   fMax_1[2][2] = 28.4575004578;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 3;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<3;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
